<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251202221426 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE ai_risk_scores (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, risk_level VARCHAR(20) NOT NULL, factors JSON DEFAULT NULL, predictions JSON DEFAULT NULL, calculated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, student_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_ABFC8A85CB944F1A ON ai_risk_scores (student_id)');
        $this->addSql('CREATE TABLE audit_logs (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(100) NOT NULL, entity VARCHAR(100) NOT NULL, entity_id INT DEFAULT NULL, changes JSON DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, user_agent TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_audit_created ON audit_logs (created_at)');
        $this->addSql('CREATE INDEX idx_audit_user ON audit_logs (user_id)');
        $this->addSql('CREATE TABLE chat_messages (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, attachments JSON DEFAULT NULL, read_by JSON DEFAULT NULL, sent_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, room_id INT NOT NULL, sender_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EF20C9A654177093 ON chat_messages (room_id)');
        $this->addSql('CREATE INDEX IDX_EF20C9A6F624B39D ON chat_messages (sender_id)');
        $this->addSql('CREATE TABLE chat_rooms (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) DEFAULT NULL, type VARCHAR(20) NOT NULL, participants JSON DEFAULT NULL, metadata JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE contracts (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, contract_number VARCHAR(50) NOT NULL, resolution_number VARCHAR(50) DEFAULT NULL, total_amount NUMERIC(10, 2) NOT NULL, installments INT DEFAULT NULL, generated_pdf VARCHAR(255) DEFAULT NULL, signed_pdf VARCHAR(255) DEFAULT NULL, signature_metadata JSON DEFAULT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, enrollment_id INT NOT NULL, parent_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_950A973AAD0FA19 ON contracts (contract_number)');
        $this->addSql('CREATE INDEX IDX_950A9738F7DB25B ON contracts (enrollment_id)');
        $this->addSql('CREATE INDEX IDX_950A973727ACA70 ON contracts (parent_id)');
        $this->addSql('CREATE TABLE enrollments (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, academic_year INT NOT NULL, status VARCHAR(20) NOT NULL, enrollment_date DATE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, student_id INT NOT NULL, grade_id INT NOT NULL, section_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CCD8C132CB944F1A ON enrollments (student_id)');
        $this->addSql('CREATE INDEX IDX_CCD8C132FE19A1A8 ON enrollments (grade_id)');
        $this->addSql('CREATE INDEX IDX_CCD8C132D823E37A ON enrollments (section_id)');
        $this->addSql('CREATE TABLE grades (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, level VARCHAR(50) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE notifications (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(200) NOT NULL, message TEXT NOT NULL, type VARCHAR(50) NOT NULL, data JSON DEFAULT NULL, read BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6000B0D3A76ED395 ON notifications (user_id)');
        $this->addSql('CREATE TABLE parents (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, personal_id VARCHAR(20) DEFAULT NULL, profession VARCHAR(100) DEFAULT NULL, workplace VARCHAR(200) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FD501D6A5D430949 ON parents (personal_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FD501D6AA76ED395 ON parents (user_id)');
        $this->addSql('CREATE TABLE parent_student (parent_entity_id INT NOT NULL, student_id INT NOT NULL, PRIMARY KEY (parent_entity_id, student_id))');
        $this->addSql('CREATE INDEX IDX_C56BDB75706E52B3 ON parent_student (parent_entity_id)');
        $this->addSql('CREATE INDEX IDX_C56BDB75CB944F1A ON parent_student (student_id)');
        $this->addSql('CREATE TABLE payments (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount NUMERIC(10, 2) NOT NULL, payment_type VARCHAR(20) NOT NULL, payment_method VARCHAR(50) DEFAULT NULL, status VARCHAR(20) NOT NULL, due_date DATE DEFAULT NULL, paid_date DATE DEFAULT NULL, receipt VARCHAR(255) DEFAULT NULL, metadata JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, enrollment_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_65D29B328F7DB25B ON payments (enrollment_id)');
        $this->addSql('CREATE TABLE schedules (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, day_of_week INT NOT NULL, start_time TIME(0) WITHOUT TIME ZONE NOT NULL, end_time TIME(0) WITHOUT TIME ZONE NOT NULL, classroom VARCHAR(50) DEFAULT NULL, academic_year INT NOT NULL, section_id INT NOT NULL, subject_id INT NOT NULL, teacher_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_313BDC8ED823E37A ON schedules (section_id)');
        $this->addSql('CREATE INDEX IDX_313BDC8E23EDC87 ON schedules (subject_id)');
        $this->addSql('CREATE INDEX IDX_313BDC8E41807E1D ON schedules (teacher_id)');
        $this->addSql('CREATE TABLE sections (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(10) NOT NULL, capacity INT DEFAULT NULL, academic_year INT NOT NULL, grade_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2B964398FE19A1A8 ON sections (grade_id)');
        $this->addSql('CREATE TABLE students (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, personal_id VARCHAR(20) DEFAULT NULL, birth_date DATE DEFAULT NULL, gender VARCHAR(10) DEFAULT NULL, nationality VARCHAR(50) DEFAULT NULL, address TEXT DEFAULT NULL, emergency_contact JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A4698DB25D430949 ON students (personal_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A4698DB2A76ED395 ON students (user_id)');
        $this->addSql('CREATE TABLE subjects (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, code VARCHAR(20) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AB25991777153098 ON subjects (code)');
        $this->addSql('CREATE TABLE teachers (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, specialization VARCHAR(100) DEFAULT NULL, hire_date DATE DEFAULT NULL, birth_date DATE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_ED071FF6A76ED395 ON teachers (user_id)');
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(255) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, first_name VARCHAR(100) DEFAULT NULL, last_name VARCHAR(100) DEFAULT NULL, phone VARCHAR(20) DEFAULT NULL, avatar VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_active BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON users (email)');
        $this->addSql('ALTER TABLE ai_risk_scores ADD CONSTRAINT FK_ABFC8A85CB944F1A FOREIGN KEY (student_id) REFERENCES students (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE audit_logs ADD CONSTRAINT FK_D62F2858A76ED395 FOREIGN KEY (user_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE chat_messages ADD CONSTRAINT FK_EF20C9A654177093 FOREIGN KEY (room_id) REFERENCES chat_rooms (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE chat_messages ADD CONSTRAINT FK_EF20C9A6F624B39D FOREIGN KEY (sender_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE contracts ADD CONSTRAINT FK_950A9738F7DB25B FOREIGN KEY (enrollment_id) REFERENCES enrollments (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE contracts ADD CONSTRAINT FK_950A973727ACA70 FOREIGN KEY (parent_id) REFERENCES parents (id)');
        $this->addSql('ALTER TABLE enrollments ADD CONSTRAINT FK_CCD8C132CB944F1A FOREIGN KEY (student_id) REFERENCES students (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE enrollments ADD CONSTRAINT FK_CCD8C132FE19A1A8 FOREIGN KEY (grade_id) REFERENCES grades (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE enrollments ADD CONSTRAINT FK_CCD8C132D823E37A FOREIGN KEY (section_id) REFERENCES sections (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notifications ADD CONSTRAINT FK_6000B0D3A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE parents ADD CONSTRAINT FK_FD501D6AA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE parent_student ADD CONSTRAINT FK_C56BDB75706E52B3 FOREIGN KEY (parent_entity_id) REFERENCES parents (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE parent_student ADD CONSTRAINT FK_C56BDB75CB944F1A FOREIGN KEY (student_id) REFERENCES students (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE payments ADD CONSTRAINT FK_65D29B328F7DB25B FOREIGN KEY (enrollment_id) REFERENCES enrollments (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE schedules ADD CONSTRAINT FK_313BDC8ED823E37A FOREIGN KEY (section_id) REFERENCES sections (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE schedules ADD CONSTRAINT FK_313BDC8E23EDC87 FOREIGN KEY (subject_id) REFERENCES subjects (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE schedules ADD CONSTRAINT FK_313BDC8E41807E1D FOREIGN KEY (teacher_id) REFERENCES teachers (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sections ADD CONSTRAINT FK_2B964398FE19A1A8 FOREIGN KEY (grade_id) REFERENCES grades (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE students ADD CONSTRAINT FK_A4698DB2A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE teachers ADD CONSTRAINT FK_ED071FF6A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE ai_risk_scores DROP CONSTRAINT FK_ABFC8A85CB944F1A');
        $this->addSql('ALTER TABLE audit_logs DROP CONSTRAINT FK_D62F2858A76ED395');
        $this->addSql('ALTER TABLE chat_messages DROP CONSTRAINT FK_EF20C9A654177093');
        $this->addSql('ALTER TABLE chat_messages DROP CONSTRAINT FK_EF20C9A6F624B39D');
        $this->addSql('ALTER TABLE contracts DROP CONSTRAINT FK_950A9738F7DB25B');
        $this->addSql('ALTER TABLE contracts DROP CONSTRAINT FK_950A973727ACA70');
        $this->addSql('ALTER TABLE enrollments DROP CONSTRAINT FK_CCD8C132CB944F1A');
        $this->addSql('ALTER TABLE enrollments DROP CONSTRAINT FK_CCD8C132FE19A1A8');
        $this->addSql('ALTER TABLE enrollments DROP CONSTRAINT FK_CCD8C132D823E37A');
        $this->addSql('ALTER TABLE notifications DROP CONSTRAINT FK_6000B0D3A76ED395');
        $this->addSql('ALTER TABLE parents DROP CONSTRAINT FK_FD501D6AA76ED395');
        $this->addSql('ALTER TABLE parent_student DROP CONSTRAINT FK_C56BDB75706E52B3');
        $this->addSql('ALTER TABLE parent_student DROP CONSTRAINT FK_C56BDB75CB944F1A');
        $this->addSql('ALTER TABLE payments DROP CONSTRAINT FK_65D29B328F7DB25B');
        $this->addSql('ALTER TABLE schedules DROP CONSTRAINT FK_313BDC8ED823E37A');
        $this->addSql('ALTER TABLE schedules DROP CONSTRAINT FK_313BDC8E23EDC87');
        $this->addSql('ALTER TABLE schedules DROP CONSTRAINT FK_313BDC8E41807E1D');
        $this->addSql('ALTER TABLE sections DROP CONSTRAINT FK_2B964398FE19A1A8');
        $this->addSql('ALTER TABLE students DROP CONSTRAINT FK_A4698DB2A76ED395');
        $this->addSql('ALTER TABLE teachers DROP CONSTRAINT FK_ED071FF6A76ED395');
        $this->addSql('DROP TABLE ai_risk_scores');
        $this->addSql('DROP TABLE audit_logs');
        $this->addSql('DROP TABLE chat_messages');
        $this->addSql('DROP TABLE chat_rooms');
        $this->addSql('DROP TABLE contracts');
        $this->addSql('DROP TABLE enrollments');
        $this->addSql('DROP TABLE grades');
        $this->addSql('DROP TABLE notifications');
        $this->addSql('DROP TABLE parents');
        $this->addSql('DROP TABLE parent_student');
        $this->addSql('DROP TABLE payments');
        $this->addSql('DROP TABLE schedules');
        $this->addSql('DROP TABLE sections');
        $this->addSql('DROP TABLE students');
        $this->addSql('DROP TABLE subjects');
        $this->addSql('DROP TABLE teachers');
        $this->addSql('DROP TABLE users');
    }
}
