<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTVRPwp8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTVRPwp8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTVRPwp8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTVRPwp8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTVRPwp8\App_KernelDevDebugContainer([
    'container.build_hash' => 'TVRPwp8',
    'container.build_id' => '3a4d48b2',
    'container.build_time' => 1764712269,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTVRPwp8');
