<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CmsMenusPrivilegesSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
['id' =>3, 'id_cms_menus' => 2, 'id_cms_privileges' => 1],
['id' => 4, 'id_cms_menus' => 3, 'id_cms_privileges' => 1],
['id' => 9, 'id_cms_menus' => 8, 'id_cms_privileges' => 1],
['id' => 10, 'id_cms_menus' => 9, 'id_cms_privileges' => 1],
['id' => 19, 'id_cms_menus' => 13, 'id_cms_privileges' => 1],
['id' => 20, 'id_cms_menus' => 14, 'id_cms_privileges' => 1],
['id' => 21, 'id_cms_menus' => 15, 'id_cms_privileges' => 1],
['id' => 22, 'id_cms_menus' => 16, 'id_cms_privileges' => 1],
['id' => 24, 'id_cms_menus' => 18, 'id_cms_privileges' => 1],
['id' => 26, 'id_cms_menus' => 20, 'id_cms_privileges' => 1],
['id' => 27, 'id_cms_menus' => 21, 'id_cms_privileges' => 1],
['id' => 28, 'id_cms_menus' => 22, 'id_cms_privileges' => 1],
['id' => 41, 'id_cms_menus' => 27, 'id_cms_privileges' => 2],
['id' => 42, 'id_cms_menus' => 27, 'id_cms_privileges' => 1],
['id' => 63, 'id_cms_menus' => 23, 'id_cms_privileges' => 5],
['id' => 64, 'id_cms_menus' => 23, 'id_cms_privileges' => 1],
['id' => 72, 'id_cms_menus' => 29, 'id_cms_privileges' => 7],
['id' => 73, 'id_cms_menus' => 29, 'id_cms_privileges' => 8],
['id' => 74, 'id_cms_menus' => 29, 'id_cms_privileges' => 1],
['id' => 75, 'id_cms_menus' => 19, 'id_cms_privileges' => 7],
['id' => 76, 'id_cms_menus' => 19, 'id_cms_privileges' => 8],
['id' => 77, 'id_cms_menus' => 19, 'id_cms_privileges' => 1],
['id' => 82, 'id_cms_menus' => 34, 'id_cms_privileges' => 1],
['id' => 83, 'id_cms_menus' => 35, 'id_cms_privileges' => 1],
['id' => 84, 'id_cms_menus' => 36, 'id_cms_privileges' => 1],
['id' => 85, 'id_cms_menus' => 37, 'id_cms_privileges' => 1],
['id' => 86, 'id_cms_menus' => 38, 'id_cms_privileges' => 1],
['id' => 87, 'id_cms_menus' => 33, 'id_cms_privileges' => 7],
['id' => 88, 'id_cms_menus' => 33, 'id_cms_privileges' => 5],
['id' => 89, 'id_cms_menus' => 33, 'id_cms_privileges' => 1],
['id' => 90, 'id_cms_menus' => 39, 'id_cms_privileges' => 7],
['id' => 91, 'id_cms_menus' => 39, 'id_cms_privileges' => 5],
['id' => 92, 'id_cms_menus' => 39, 'id_cms_privileges' => 1],
['id' => 96, 'id_cms_menus' => 41, 'id_cms_privileges' => 7],
['id' => 97, 'id_cms_menus' => 41, 'id_cms_privileges' => 5],
['id' => 98, 'id_cms_menus' => 41, 'id_cms_privileges' => 1],
['id' => 99, 'id_cms_menus' => 31, 'id_cms_privileges' => 7],
['id' => 100, 'id_cms_menus' => 31, 'id_cms_privileges' => 5],
['id' => 101, 'id_cms_menus' => 31, 'id_cms_privileges' => 1],
['id' => 102, 'id_cms_menus' => 42, 'id_cms_privileges' => 7],
['id' => 103, 'id_cms_menus' => 42, 'id_cms_privileges' => 5],
['id' => 104, 'id_cms_menus' => 42, 'id_cms_privileges' => 1],
['id' => 112, 'id_cms_menus' => 25, 'id_cms_privileges' => 6],
['id' => 113, 'id_cms_menus' => 25, 'id_cms_privileges' => 1],
['id' => 116, 'id_cms_menus' => 44, 'id_cms_privileges' => 7],
['id' => 117, 'id_cms_menus' => 44, 'id_cms_privileges' => 6],
['id' => 118, 'id_cms_menus' => 44, 'id_cms_privileges' => 1],
['id' => 119, 'id_cms_menus' => 45, 'id_cms_privileges' => 7],
['id' => 120, 'id_cms_menus' => 45, 'id_cms_privileges' => 5],
['id' => 121, 'id_cms_menus' => 45, 'id_cms_privileges' => 1],
['id' => 147, 'id_cms_menus' => 47, 'id_cms_privileges' => 6],
['id' => 153, 'id_cms_menus' => 50, 'id_cms_privileges' => 7],
['id' => 154, 'id_cms_menus' => 50, 'id_cms_privileges' => 8],
['id' => 155, 'id_cms_menus' => 50, 'id_cms_privileges' => 5],
['id' => 156, 'id_cms_menus' => 50, 'id_cms_privileges' => 1],
['id' => 157, 'id_cms_menus' => 30, 'id_cms_privileges' => 7],
['id' => 158, 'id_cms_menus' => 30, 'id_cms_privileges' => 3],
['id' => 159, 'id_cms_menus' => 30, 'id_cms_privileges' => 5],
['id' => 160, 'id_cms_menus' => 30, 'id_cms_privileges' => 1],
['id' => 161, 'id_cms_menus' => 43, 'id_cms_privileges' => 6],
['id' => 165, 'id_cms_menus' => 24, 'id_cms_privileges' => 7],
['id' => 166, 'id_cms_menus' => 24, 'id_cms_privileges' => 3],
['id' => 167, 'id_cms_menus' => 24, 'id_cms_privileges' => 5],
['id' => 168, 'id_cms_menus' => 24, 'id_cms_privileges' => 1],
['id' => 173, 'id_cms_menus' => 49, 'id_cms_privileges' => 8],
['id' => 174, 'id_cms_menus' => 49, 'id_cms_privileges' => 1],
['id' => 175, 'id_cms_menus' => 17, 'id_cms_privileges' => 7],
['id' => 176, 'id_cms_menus' => 17, 'id_cms_privileges' => 8],
['id' => 177, 'id_cms_menus' => 17, 'id_cms_privileges' => 1],
['id' => 178, 'id_cms_menus' => 26, 'id_cms_privileges' => 8],
['id' => 179, 'id_cms_menus' => 26, 'id_cms_privileges' => 6],
['id' => 180, 'id_cms_menus' => 26, 'id_cms_privileges' => 1],
['id' => 183, 'id_cms_menus' => 48, 'id_cms_privileges' => 5],
['id' => 184, 'id_cms_menus' => 48, 'id_cms_privileges' => 1],
['id' => 188, 'id_cms_menus' => 10, 'id_cms_privileges' => 7],
['id' => 189, 'id_cms_menus' => 10, 'id_cms_privileges' => 8],
['id' => 190, 'id_cms_menus' => 10, 'id_cms_privileges' => 1],
['id' => 191, 'id_cms_menus' => 4, 'id_cms_privileges' => 7],
['id' => 192, 'id_cms_menus' => 4, 'id_cms_privileges' => 8],
['id' => 193, 'id_cms_menus' => 4, 'id_cms_privileges' => 1],
['id' => 194, 'id_cms_menus' => 6, 'id_cms_privileges' => 8],
['id' => 195, 'id_cms_menus' => 6, 'id_cms_privileges' => 1],
['id' => 196, 'id_cms_menus' => 5, 'id_cms_privileges' => 7],
['id' => 197, 'id_cms_menus' => 5, 'id_cms_privileges' => 8],
['id' => 198, 'id_cms_menus' => 5, 'id_cms_privileges' => 1],
['id' => 199, 'id_cms_menus' => 7, 'id_cms_privileges' => 7],
['id' => 200, 'id_cms_menus' => 7, 'id_cms_privileges' => 8],
['id' => 201, 'id_cms_menus' => 7, 'id_cms_privileges' => 1],
['id' => 202, 'id_cms_menus' => 1, 'id_cms_privileges' => 7],
['id' => 203, 'id_cms_menus' => 1, 'id_cms_privileges' => 8],
['id' => 204, 'id_cms_menus' => 1, 'id_cms_privileges' => 1],
['id' => 205, 'id_cms_menus' => 46, 'id_cms_privileges' => 8],
['id' => 206, 'id_cms_menus' => 46, 'id_cms_privileges' => 1],
['id' => 207, 'id_cms_menus' => 11, 'id_cms_privileges' => 5],
['id' => 208, 'id_cms_menus' => 11, 'id_cms_privileges' => 1],
['id' => 209, 'id_cms_menus' => 40, 'id_cms_privileges' => 7],
['id' => 210, 'id_cms_menus' => 40, 'id_cms_privileges' => 5],
['id' => 211, 'id_cms_menus' => 40, 'id_cms_privileges' => 1],
['id' => 212, 'id_cms_menus' => 52, 'id_cms_privileges' => 3],
['id' => 213, 'id_cms_menus' => 53, 'id_cms_privileges' => 1],
['id' => 214, 'id_cms_menus' => 54, 'id_cms_privileges' => 1],
['id' => 220, 'id_cms_menus' => 57, 'id_cms_privileges' => 1],
['id' => 221, 'id_cms_menus' => 58, 'id_cms_privileges' => 1],
['id' => 223, 'id_cms_menus' => 12, 'id_cms_privileges' => 7],
['id' => 224, 'id_cms_menus' => 12, 'id_cms_privileges' => 8],
['id' => 225, 'id_cms_menus' => 12, 'id_cms_privileges' => 1],
['id' => 226, 'id_cms_menus' => 55, 'id_cms_privileges' => 1],
['id' => 231, 'id_cms_menus' => 59, 'id_cms_privileges' => 6],
['id' => 232, 'id_cms_menus' => 59, 'id_cms_privileges' => 1],
['id' => 236, 'id_cms_menus' => 62, 'id_cms_privileges' => 3],
['id' => 237, 'id_cms_menus' => 61, 'id_cms_privileges' => 4],
['id' => 238, 'id_cms_menus' => 61, 'id_cms_privileges' => 3],
['id' => 239, 'id_cms_menus' => 61, 'id_cms_privileges' => 1],
['id' => 240, 'id_cms_menus' => 60, 'id_cms_privileges' => 2],
['id' => 241, 'id_cms_menus' => 60, 'id_cms_privileges' => 1],
['id' => 242, 'id_cms_menus' => 51, 'id_cms_privileges' => 5],
['id' => 243, 'id_cms_menus' => 51, 'id_cms_privileges' => 1],
['id' => 246, 'id_cms_menus' => 56, 'id_cms_privileges' => 8],
['id' => 247, 'id_cms_menus' => 56, 'id_cms_privileges' => 5],
['id' => 248, 'id_cms_menus' => 56, 'id_cms_privileges' => 1],
['id' => 251, 'id_cms_menus' => 63, 'id_cms_privileges' => 1],
['id' => 252, 'id_cms_menus' => 64, 'id_cms_privileges' => 1],
['id' => 253, 'id_cms_menus' => 65, 'id_cms_privileges' => 1],
['id' => 254, 'id_cms_menus' => 66, 'id_cms_privileges' => 6],
['id' => 255, 'id_cms_menus' => 66, 'id_cms_privileges' => 1],
['id' => 256, 'id_cms_menus' => 67, 'id_cms_privileges' => 3],
['id' => 257, 'id_cms_menus' => 67, 'id_cms_privileges' => 1],
['id' => 258, 'id_cms_menus' => 68, 'id_cms_privileges' => 7],
['id' => 259, 'id_cms_menus' => 68, 'id_cms_privileges' => 8],
['id' => 260, 'id_cms_menus' => 68, 'id_cms_privileges' => 5],
['id' => 261, 'id_cms_menus' => 68, 'id_cms_privileges' => 1],
['id' => 262, 'id_cms_menus' => 69, 'id_cms_privileges' => 7],
['id' => 263, 'id_cms_menus' => 69, 'id_cms_privileges' => 3],
['id' => 264, 'id_cms_menus' => 69, 'id_cms_privileges' => 5],
['id' => 265, 'id_cms_menus' => 69, 'id_cms_privileges' => 1],
['id' => 270, 'id_cms_menus' => 72, 'id_cms_privileges' => 7],
['id' => 271, 'id_cms_menus' => 72, 'id_cms_privileges' => 1],
['id' => 272, 'id_cms_menus' => 71, 'id_cms_privileges' => 7],
['id' => 273, 'id_cms_menus' => 71, 'id_cms_privileges' => 1],
['id' => 277, 'id_cms_menus' => 73, 'id_cms_privileges' => 7],
['id' => 278, 'id_cms_menus' => 73, 'id_cms_privileges' => 5],
['id' => 279, 'id_cms_menus' => 73, 'id_cms_privileges' => 1],
['id' => 280, 'id_cms_menus' => 74, 'id_cms_privileges' => 7],
['id' => 281, 'id_cms_menus' => 74, 'id_cms_privileges' => 5],
['id' => 282, 'id_cms_menus' => 74, 'id_cms_privileges' => 1],
['id' => 283, 'id_cms_menus' => 75, 'id_cms_privileges' => 7],
['id' => 284, 'id_cms_menus' => 75, 'id_cms_privileges' => 5],
['id' => 285, 'id_cms_menus' => 75, 'id_cms_privileges' => 1],
['id' => 289, 'id_cms_menus' => 77, 'id_cms_privileges' => 7],
['id' => 290, 'id_cms_menus' => 77, 'id_cms_privileges' => 8],
['id' => 291, 'id_cms_menus' => 77, 'id_cms_privileges' => 5],
['id' => 292, 'id_cms_menus' => 77, 'id_cms_privileges' => 1],
['id' => 293, 'id_cms_menus' => 78, 'id_cms_privileges' => 7],
['id' => 294, 'id_cms_menus' => 78, 'id_cms_privileges' => 1],
['id' => 295, 'id_cms_menus' => 79, 'id_cms_privileges' => 7],
['id' => 296, 'id_cms_menus' => 79, 'id_cms_privileges' => 1],
['id' => 297, 'id_cms_menus' => 80, 'id_cms_privileges' => 1],
['id' => 298, 'id_cms_menus' => 81, 'id_cms_privileges' => 7],
['id' => 299, 'id_cms_menus' => 81, 'id_cms_privileges' => 1],
['id' => 300, 'id_cms_menus' => 82, 'id_cms_privileges' => 7],
['id' => 301, 'id_cms_menus' => 82, 'id_cms_privileges' => 5],
['id' => 302, 'id_cms_menus' => 82, 'id_cms_privileges' => 1],
['id' => 303, 'id_cms_menus' => 76, 'id_cms_privileges' => 7],
['id' => 304, 'id_cms_menus' => 76, 'id_cms_privileges' => 1],
['id' => 305, 'id_cms_menus' => 83, 'id_cms_privileges' => 7],
['id' => 306, 'id_cms_menus' => 83, 'id_cms_privileges' => 1],
['id' => 307, 'id_cms_menus' => 84, 'id_cms_privileges' => 7],
['id' => 308, 'id_cms_menus' => 84, 'id_cms_privileges' => 1],
['id' => 309, 'id_cms_menus' => 85, 'id_cms_privileges' => 7],
['id' => 310, 'id_cms_menus' => 85, 'id_cms_privileges' => 1],
['id' => 313, 'id_cms_menus' => 86, 'id_cms_privileges' => 7],
['id' => 314, 'id_cms_menus' => 86, 'id_cms_privileges' => 1],
['id' => 315, 'id_cms_menus' => 87, 'id_cms_privileges' => 7],
['id' => 316, 'id_cms_menus' => 87, 'id_cms_privileges' => 1],
['id' => 317, 'id_cms_menus' => 88, 'id_cms_privileges' => 7],
['id' => 318, 'id_cms_menus' => 88, 'id_cms_privileges' => 1],
['id' => 319, 'id_cms_menus' => 89, 'id_cms_privileges' => 7],
['id' => 320, 'id_cms_menus' => 89, 'id_cms_privileges' => 1],
['id' => 323, 'id_cms_menus' => 90, 'id_cms_privileges' => 7],
['id' => 324, 'id_cms_menus' => 90, 'id_cms_privileges' => 8],
['id' => 325, 'id_cms_menus' => 90, 'id_cms_privileges' => 1],
['id' => 328, 'id_cms_menus' => 32, 'id_cms_privileges' => 5],
['id' => 329, 'id_cms_menus' => 32, 'id_cms_privileges' => 1],
['id' => 330, 'id_cms_menus' => 91, 'id_cms_privileges' => 2],
['id' => 331, 'id_cms_menus' => 92, 'id_cms_privileges' => 7],
['id' => 332, 'id_cms_menus' => 92, 'id_cms_privileges' => 8],
['id' => 333, 'id_cms_menus' => 92, 'id_cms_privileges' => 1],
['id' => 334, 'id_cms_menus' => 93, 'id_cms_privileges' => 7],
['id' => 335, 'id_cms_menus' => 93, 'id_cms_privileges' => 8],
['id' => 336, 'id_cms_menus' => 93, 'id_cms_privileges' => 5],
['id' => 337, 'id_cms_menus' => 93, 'id_cms_privileges' => 1],
['id' => 338, 'id_cms_menus' => 94, 'id_cms_privileges' => 7],
['id' => 339, 'id_cms_menus' => 94, 'id_cms_privileges' => 8],
['id' => 340, 'id_cms_menus' => 94, 'id_cms_privileges' => 1],
['id' => 341, 'id_cms_menus' => 95, 'id_cms_privileges' => 3],
['id' => 342, 'id_cms_menus' => 96, 'id_cms_privileges' => 3],
['id' => 343, 'id_cms_menus' => 97, 'id_cms_privileges' => 3],
['id' => 344, 'id_cms_menus' => 98, 'id_cms_privileges' => 7],
['id' => 345, 'id_cms_menus' => 98, 'id_cms_privileges' => 8],
['id' => 346, 'id_cms_menus' => 98, 'id_cms_privileges' => 5],
['id' => 347, 'id_cms_menus' => 98, 'id_cms_privileges' => 1],
['id' => 350, 'id_cms_menus' => 99, 'id_cms_privileges' => 6],
['id' => 363, 'id_cms_menus' => 28, 'id_cms_privileges' => 2],
['id' => 364, 'id_cms_menus' => 28, 'id_cms_privileges' => 1],
['id' => 365, 'id_cms_menus' => 100, 'id_cms_privileges' => 6],
['id' => 366, 'id_cms_menus' => 100, 'id_cms_privileges' => 2],
['id' => 367, 'id_cms_menus' => 101, 'id_cms_privileges' => 7],
['id' => 368, 'id_cms_menus' => 101, 'id_cms_privileges' => 8],
['id' => 369, 'id_cms_menus' => 101, 'id_cms_privileges' => 9],
['id' => 370, 'id_cms_menus' => 101, 'id_cms_privileges' => 6],
['id' => 371, 'id_cms_menus' => 101, 'id_cms_privileges' => 2],
['id' => 372, 'id_cms_menus' => 101, 'id_cms_privileges' => 5],
['id' => 373, 'id_cms_menus' => 101, 'id_cms_privileges' => 1],
['id' => 374, 'id_cms_menus' => 70, 'id_cms_privileges' => 7],
['id' => 375, 'id_cms_menus' => 70, 'id_cms_privileges' => 1],
['id' => 376, 'id_cms_menus' => 102, 'id_cms_privileges' => 1],
['id' => 377, 'id_cms_menus' => 103, 'id_cms_privileges' => 9],
['id' => 378, 'id_cms_menus' => 103, 'id_cms_privileges' => 1],
['id' => 379, 'id_cms_menus' => 104, 'id_cms_privileges' => 5],
['id' => 380, 'id_cms_menus' => 104, 'id_cms_privileges' => 1],
['id' => 381, 'id_cms_menus' => 105, 'id_cms_privileges' => 4],
['id' => 382, 'id_cms_menus' => 105, 'id_cms_privileges' => 3],

['id' => 384, 'id_cms_menus' => 106, 'id_cms_privileges' => 1],
['id' => 385, 'id_cms_menus' => 107, 'id_cms_privileges' => 7],
['id' => 386, 'id_cms_menus' => 107, 'id_cms_privileges' => 1],




        ];
        foreach ($data as $item) {
            DB::table('cms_menus_privileges')->updateOrInsert(
                [
                    'id_cms_menus' => $item['id_cms_menus'],
                    'id_cms_privileges' => $item['id_cms_privileges'],
                ],
                $item
            );
        }
    }
}
